spring:
  application:
    name: finalfantasy
  main:
    web-application-type: none
  docker:
    compose:
      enabled: false
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  profiles:
    active: local

# Server port configurations
server:
  port: ${finalfantasy.server.http.port:8080}

finalfantasy:
  server:
    http:
      port: 8080
    grpc:
      port: 9090
      enabled: true
    vertx:
      http-port: 8081
      socket-port: 8082

# gRPC server configuration
grpc:
  server:
    port: ${finalfantasy.server.grpc.port:9090}
    enabled: ${finalfantasy.server.grpc.enabled:true}
